
package com.oculusinfo.ncompass.authentication;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "UserDataFault", targetNamespace = "http://oculusinfo.com/ncompass/authentication")
public class UserDataFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UserDataFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UserDataFaultMsg(String message, UserDataFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UserDataFaultMsg(String message, UserDataFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oculusinfo.ncompass.authentication.UserDataFault
     */
    public UserDataFault getFaultInfo() {
        return faultInfo;
    }

}
