
package dias;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.DistinguisedNameListType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetAffiliationResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetAllUserGroupsResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetCitizenshipResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetFormalAccessResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetGroupDNRequestType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetGroupDNResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetGroupMembersByDNRequestType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetGroupMembersRequestType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetOrganizationResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetSecurityAttributesAndGroupsResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetSecurityAttributesResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetUserClearanceResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.GetUserGroupsResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.IsMemberOfByDNRequestType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.IsMemberOfRequestType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.IsMemberOfResponseType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.UserGroupRequestType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.UserIdentifierType;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.WhitePageAttributesType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DIASMessageReceiver", targetNamespace = "urn:dias")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    dias.ObjectFactory.class,
    gov.ic.dodiis.service.security.dias.v2_1.authservice.ObjectFactory.class
})
public interface DIASMessageReceiver {


    /**
     * 
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetAllUserGroupsResponseType
     * @throws Error
     */
    @WebMethod(action = "getAllGroups")
    @WebResult(name = "getAllGroupsResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getAllGroupsResponse")
    public GetAllUserGroupsResponseType getAllGroups()
        throws Error
    ;

    /**
     * 
     * @param getAllUserGroupsRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetAllUserGroupsResponseType
     * @throws Error
     */
    @WebMethod(action = "getAllUserGroups1")
    @WebResult(name = "getAllUserGroupsResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getAllUserGroupsResponse")
    public GetAllUserGroupsResponseType getAllUserGroups(
        @WebParam(name = "getAllUserGroupsRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getAllUserGroupsRequest")
        UserIdentifierType getAllUserGroupsRequest)
        throws Error
    ;

    /**
     * 
     * @param isMemberOfRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.IsMemberOfResponseType
     * @throws Error
     */
    @WebMethod(action = "isMemberOf")
    @WebResult(name = "isMemberOfResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "isMemberOfResponse")
    public IsMemberOfResponseType isMemberOf(
        @WebParam(name = "isMemberOfRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "isMemberOfRequest")
        IsMemberOfRequestType isMemberOfRequest)
        throws Error
    ;

    /**
     * 
     * @param isMemberOfByDNRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.IsMemberOfResponseType
     * @throws Error
     */
    @WebMethod(action = "isMemberOfByDN")
    @WebResult(name = "isMemberOfResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "isMemberOfResponse")
    public IsMemberOfResponseType isMemberOfByDN(
        @WebParam(name = "isMemberOfByDNRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "isMemberOfByDNRequest")
        IsMemberOfByDNRequestType isMemberOfByDNRequest)
        throws Error
    ;

    /**
     * 
     * @param getGroupDNRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetGroupDNResponseType
     * @throws Error
     */
    @WebMethod(action = "getGroupDN")
    @WebResult(name = "getGroupDNResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getGroupDNResponse")
    public GetGroupDNResponseType getGroupDN(
        @WebParam(name = "getGroupDNRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getGroupDNRequest")
        GetGroupDNRequestType getGroupDNRequest)
        throws Error
    ;

    /**
     * 
     * @param getGroupMembersByDNRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.DistinguisedNameListType
     * @throws Error
     */
    @WebMethod(action = "getGroupMembersByDN")
    @WebResult(name = "getGroupMembersResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getGroupMembersResponse")
    public DistinguisedNameListType getGroupMembersByDN(
        @WebParam(name = "getGroupMembersByDNRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getGroupMembersByDNRequest")
        GetGroupMembersByDNRequestType getGroupMembersByDNRequest)
        throws Error
    ;

    /**
     * 
     * @param getGroupMembersRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.DistinguisedNameListType
     * @throws Error
     */
    @WebMethod(action = "getGroupMembers")
    @WebResult(name = "getGroupMembersResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getGroupMembersResponse")
    public DistinguisedNameListType getGroupMembers(
        @WebParam(name = "getGroupMembersRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getGroupMembersRequest")
        GetGroupMembersRequestType getGroupMembersRequest)
        throws Error
    ;

    /**
     * 
     * @param getUserFormalAccessRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetFormalAccessResponseType
     * @throws Error
     */
    @WebMethod(action = "getUserFormalAccess")
    @WebResult(name = "getFormalAccessResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getFormalAccessResponse")
    public GetFormalAccessResponseType getUserFormalAccess(
        @WebParam(name = "getUserFormalAccessRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getUserFormalAccessRequest")
        UserIdentifierType getUserFormalAccessRequest)
        throws Error
    ;

    /**
     * 
     * @param getUserOrgRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetOrganizationResponseType
     * @throws Error
     */
    @WebMethod(action = "getUserOrganization")
    @WebResult(name = "getOrganizationResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getOrganizationResponse")
    public GetOrganizationResponseType getUserOrganization(
        @WebParam(name = "getUserOrgRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getUserOrgRequest")
        UserIdentifierType getUserOrgRequest)
        throws Error
    ;

    /**
     * 
     * @param getUserCitizenshipRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetCitizenshipResponseType
     * @throws Error
     */
    @WebMethod(action = "getUserCitizenship")
    @WebResult(name = "getCitizenshipResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getCitizenshipResponse")
    public GetCitizenshipResponseType getUserCitizenship(
        @WebParam(name = "getUserCitizenshipRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getUserCitizenshipRequest")
        UserIdentifierType getUserCitizenshipRequest)
        throws Error
    ;

    /**
     * 
     * @param getUserAffiliationRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetAffiliationResponseType
     * @throws Error
     */
    @WebMethod(action = "getUserAffiliation")
    @WebResult(name = "getAffiliationResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getAffiliationResponse")
    public GetAffiliationResponseType getUserAffiliation(
        @WebParam(name = "getUserAffiliationRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getUserAffiliationRequest")
        UserIdentifierType getUserAffiliationRequest)
        throws Error
    ;

    /**
     * 
     * @param getGroupsRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetUserGroupsResponseType
     * @throws Error
     */
    @WebMethod(action = "getUserGroups")
    @WebResult(name = "getUserGroupsResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getGroupsResponse")
    public GetUserGroupsResponseType getUserGroups(
        @WebParam(name = "getUserGroupsRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getGroupsRequest")
        UserGroupRequestType getGroupsRequest)
        throws Error
    ;

    /**
     * 
     * @param getUserClearanceRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetUserClearanceResponseType
     * @throws Error
     */
    @WebMethod(action = "getUserClearance")
    @WebResult(name = "getClearanceResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getClearanceResponse")
    public GetUserClearanceResponseType getUserClearance(
        @WebParam(name = "getUserClearanceRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getUserClearanceRequest")
        UserIdentifierType getUserClearanceRequest)
        throws Error
    ;

    /**
     * 
     * @param getUserSecurityAttributesRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetSecurityAttributesResponseType
     * @throws Error
     */
    @WebMethod(action = "getUserSecurityAttributes")
    @WebResult(name = "getSecurityAttributesResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getSecurityAttributesResponse")
    public GetSecurityAttributesResponseType getUserSecurityAttributes(
        @WebParam(name = "getUserSecurityAttributesRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getUserSecurityAttributesRequest")
        UserIdentifierType getUserSecurityAttributesRequest)
        throws Error
    ;

    /**
     * 
     * @param getUserSecurityAttributesAndGroupsRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.GetSecurityAttributesAndGroupsResponseType
     * @throws Error
     */
    @WebMethod(action = "getUserSecurityAttributresAndGroups")
    @WebResult(name = "getSecurityAttributesAndGroupsResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getSecurityAttributesAndGroupsResponse")
    public GetSecurityAttributesAndGroupsResponseType getUserSecurityAttributesAndGroups(
        @WebParam(name = "getUserSecurityAttributesAndGroupsRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getUserSecurityAttributesAndGroupsRequest")
        UserGroupRequestType getUserSecurityAttributesAndGroupsRequest)
        throws Error
    ;

    /**
     * 
     * @param getUserInfoAttributesRequest
     * @return
     *     returns gov.ic.dodiis.service.security.dias.v2_1.authservice.WhitePageAttributesType
     * @throws Error
     */
    @WebMethod(action = "getUserInfoAttributes")
    @WebResult(name = "getUserInfoAttributesResponse", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getUserInfoAttributesResponse")
    public WhitePageAttributesType getUserInfoAttributes(
        @WebParam(name = "getUserInfoAttributesRequest", targetNamespace = "http://dias.security.service.dodiis.ic.gov/v2.1/authservice/", partName = "getUserInfoAttributesRequest")
        UserIdentifierType getUserInfoAttributesRequest)
        throws Error
    ;

}
