
package dias;

import javax.xml.ws.WebFault;
import gov.ic.dodiis.service.security.dias.v2_1.authservice.ErrorType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "error", targetNamespace = "urn:dias")
public class Error
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Error(String message, ErrorType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Error(String message, ErrorType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: gov.ic.dodiis.service.security.dias.v2_1.authservice.ErrorType
     */
    public ErrorType getFaultInfo() {
        return faultInfo;
    }

}
