/*
 * Copyright Centrifuge Systems, Inc. 2012
 * 
 * @author Centrifuge Systems, Inc.
 */
package sample.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * The Class TaskStatus.
 */
@XmlRootElement(name = "TaskStatus")
@XmlAccessorType(XmlAccessType.FIELD)
public class TaskStatus
{
    
    /** The task status. */
    @XmlElement
    public String     taskStatus;
    
    /** The task id. */
    @XmlElement
    public String     taskId;
    
    /** The session id. */
    @XmlElement
    public String     sessionId;
    
    /** The result data. */
    @XmlElement
    public ResultData resultData;
    
    /** The progress. */
    @XmlElement
    public String     progress;
    
    /** The feedback. */
    @XmlElement
    public String     feedback;
    
    /** Error message generated by the task */
    @XmlElement
    public String errorMessage;

    /** The string representation of exception thrown by the task */
    @XmlElement
    public String errorDetail;

    /** The last update. */
    @XmlElement
    public String     lastUpdate;
    
    /** The updated. */
    @XmlElement
    public String     updated;
}
