package csi.client.gwt.viz.graph.events;

public enum GraphEvents {
    DISABLE_LEGEND_MENU_TOGGLE,
    DISABLE_LOADED_GRAPH_MENU_ITEMS,
    DISABLE_TIME_PLAYER_MENU,
    DISABLE_VISIBILE_NODES_MENU_ITEMS,
    ENABLE_LEGEND_MENU_TOGGLE,
    ENABLE_LOADED_GRAPH_MENU_ITEMS,
    ENABLE_TIME_PLAYER_MENU,
    ENABLE_VISIBILE_NODES_MENU_ITEMS,
    GRAPH_DIRTY,
    GRAPH_LOAD_COMPLETE,
    LEGEND_HIDDEN,
    NODES_OR_LINKS_HIDDEN_CHANGE,
    RESET_GRAPH_DIRTY,
    SELECTION_CHANGED,
    TIME_PLAYER_ACTIVATE,
    TIME_PLAYER_PAUSE,
    TIME_PLAYER_PLAY,
    TIME_PLAYER_STOP,
    UPDATE_MENUS,
    UPDATE_MERGE_HIGHLIGHTS_FLAG;
}
